services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault-dev
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-data:/vault/data
      - ./config:/vault/config
    command: vault server -dev -dev-listen-address=0.0.0.0:8200
    networks:
      - microservices-network

  # Optional: Vault UI (if you want a separate UI container)
  vault-ui:
    image: djenriquez/vault-ui:latest
    container_name: vault-ui
    ports:
      - "9000:8000"
    environment:
      VAULT_URL_DEFAULT: http://vault:8200
      VAULT_AUTH_DEFAULT: TOKEN
    depends_on:
      - vault
    networks:
      - microservices-network

volumes:
  vault-data:
    driver: local

networks:
  microservices-network:
    driver: bridge